name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagen backend
        run: docker build -t backend:ci ./backend

      - name: Build imagen frontend
        run: docker build -t frontend:ci ./frontend

      - name: Validar docker-compose config
        run: docker compose config
